### ISSUE TITLE
查找到关键字以后，如果要替换的话，还是得用str_replace/preg_replace吗？

### ISSUE THREAD

**Issue by robhsiao** [anjuke/php-mss#1]
mss 真是个实用的扩展。

我现在的场景是做关键字替换，本想用substr，但是发现如果字典里同时含有“安居”、“安居客”这种情况时，不太好处理。

难道用str_replace/preg_replace才是最终的宿命？求解

**Comment by robhsiao** [comment]
邀请 @erning 进来讨论一下 :smile:

**Comment by erning** [comment]
返回的结果里有关键词在文本字符串中的位置，直接替换就好，不需要再查找替换。
